version: 2

defaults: &defaults
  machine:
    enabled: true
  branches:
    only:
      - master
  environment:

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: set path
          command:
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          command: |
            sudo apt update -y
            sudo apt install git python-pip python-dev build-essential -y
            git clone --recursive https://github.com/getpelican/pelican-plugins
            sudo pip install --upgrade pip
            pip install -r requirements.txt --upgrade --user
            git clone https://github.com/alexandrevicenzi/Flex.git
      - save_cache:
          key: workingdir
          paths:
            - $HOME
      - run:
          name: clean
          command:
            fab clean
      - run:
          name: build
          command:
            fab build
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            workingdir
      - run:
          name: install dependencies
          command: |
            sudo apt update -y
            sudo apt install git python-pip python-dev build-essential -y
            sudo pip install --upgrade pip
            pip install -r requirements.txt --upgrade --user
            git config --global user.email "autoburdz@burdz.net" > /dev/null 2>&1
            git config --global user.name "autoburdz" > /dev/null 2>&1
      - run:
          name: publish
          command:
            fab publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
