version: 2

defaults: &defaults
  machine:
    enabled: true
  environment:

jobs:
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "59:35:bd:9f:13:87:07:26:43:53:3e:1a:3a:5d:de:71"
      - checkout
      - run: 
          name: set path
          command:
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          command: |
            sudo apt update -y
            sudo apt install git python-pip python-dev build-essential -y
            git clone --recursive https://github.com/getpelican/pelican-plugins 
            sudo pip install --upgrade pip
            pip install -r requirements.txt --upgrade --user
            git clone https://github.com/alexandrevicenzi/Flex.git
      - run:
          name: clean
          command:
            fab clean
      - run:
          name: build
          command: | 
            fab build
      - save_cache:
          key: workingdir
          paths:
            - ~/project/
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            workingdir
      - run: 
          name: set path
          command: |
            ls -lart
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          command: |
            sudo apt update -y
            sudo apt install git python-pip python-dev build-essential -y
            sudo pip install --upgrade pip
            pip install -r requirements.txt --upgrade --user
      - run:
          name: publish
          command: 
            fab publish
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold

