version: 2

defaults: &defaults
  machine:
    enabled: true

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: set path
          command: |
            pwd
            ls -lart
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          command: |
            pwd
            ls -lart
            sudo apt update -y
            sudo apt install git python-pip python-dev build-essential -y
            git clone --recursive https://github.com/getpelican/pelican-plugins
            sudo pip install --upgrade pip
            pip install -r requirements.txt --upgrade --user
            git clone https://github.com/alexandrevicenzi/Flex.git
      - save_cache:
          key: workingdir-${CIRCLE_BUILD_NUM}
          paths:
            - ${CIRCLE_WORKING_DIRECTORY}
      - run:
          name: build
          command:
            fab rebuild
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            workingdir-${CIRCLE_BUILD_NUM}
      - run:
          name: install dependencies
          command: |
            pwd
            ls -lart
            sudo apt update -y
            sudo apt install git python-pip python-dev build-essential -y
            sudo pip install --upgrade pip
            pip install -r requirements.txt --upgrade --user
            git config --global user.email "autoburdz@burdz.net" > /dev/null 2>&1
            git config --global user.name "autoburdz" > /dev/null 2>&1
      - run:
          name: publish
          command:
            fab publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold

